### ISSUE TITLE
Feature milestones

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/android-audio-plugin-framework#4]
- v0.1
  - [x] host can load and play audio stream, applying in-process plugins that are chained.
  - [x] in-process LV2 plugins can be bridged.
- v0.2
  - [x] host can connect to service-based plugin, operate audio processing, and get results.
  - [x] service-based LV2 plugins can be bridged.
- v0.3
  - [x] host can connect to out-process plugin, operate audio processing, and get results.
  - [x] out-process LV2 plugins can be bridged.
- v0.4
  - [x] create AAP plugin that works as a synthesizer with MIDI support -> AAP-LV2 MIDI synth works.
  - [x] JUCE host works with AAP format support.
- v0.4.5
  - [x] JUCE plugin ports to AAP.
  - [x] review the entire API structure and reduce hacky parts.
  - [x] have some solid client app. -> JUCEAAPAudioPluginHost is good enough.
- v0.5
  - [x] design and implement Kotlin hosting API.
  - [ ] remote audio processor runs from within AAudio low latency (realtime-ish) audio thread.
- v0.6
  - [ ] shared containers.
  - [ ] program/bank names.
  - [ ] tail length (VST3 seems to support it, related to "release rate" / "sustain level" ?)
- v0.6
  - [ ] plugin editor GUI (we already have JuceAAPAudioPluginHost that can make changes to plugin parameters, so this issue is beyond that)

**Comment by atsushieno** [comment]
While there has been some minor updates, it's been more than a year since I came up with these tasks. Some of those remaining tasks remain important, and some of them are small details that are not worth listing for versioning milestones. I am closing this issue now and split each task into separate issues.

**Comment by atsushieno** [comment]
> remote audio processor runs from within AAudio low latency (realtime-ish) audio thread.
https://github.com/atsushieno/android-audio-plugin-framework/issues/35

> plugin editor GUI (we already have JuceAAPAudioPluginHost that can make changes to plugin parameters, so this issue is beyond that)
https://github.com/atsushieno/android-audio-plugin-framework/issues/34
