### ISSUE TITLE
meta: AAP roadmap 2021 edition

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/android-audio-plugin-framework#71]
This is a roadmap for Android Audio Plugin Framework in 2021. I don't put any concrete milestones for each task, but many of them are connected.

- [ ] (a) redesign ports
  - [x] (a1) port properties : required for UI redesign
  - [ ] (a2) audio channel configuration and audio buses
  - [ ] (a3) dynamic ports?
- [ ] (b) GUI components
  - [ ] (b1) replacement LocalPluginDetailsActivity
    - [x] (b1a) based on Jetpack Compose
    - [x] (b1b) add audio preview feature, like aaphostsample, but with nicer code
    - [ ] (b1c) based on redesigned ports - depends on (a1), optionally (a2)
  - [ ] (b2) UI protocol design
  - [ ] (b3) content - depends on (b1c)
    - [ ] (b3a) simple parameter mappings (PluginDetailsAcyivity)
    - [ ] (b3b) aqua
  - [ ] (b4) plugin in-process UI (activity) - depends on (b1c)
     - [x] (b4a) jetpack compose
     - [ ] (b4b) Flutter version?
     - [ ] (b4c) JUCE PluginEditor integration
   - [ ] (b5) out-process UI (web, wasm) - depends on (b1c)
     - [ ] (b5a) juce_emscripten, or will there be official wasm version in JUCE in time? (as there were some commits for them)
     - [ ] (b5b) MOD GUI? Is there any applicable plugin?
- [ ] (c) testing
  - [x] (c1) test utilities for connected testing (even standard ServiceTestRule is poor.)
  - [ ] (c2) test runner project/repo maybe? The existing tests in aap-core depends on aap-lv2-mda (different repo)
- [ ] (d) audio playback feature
  - [ ] (d1) get tracktion_engine working
- [x] (e) DAW
  - [x] (e1) port helio_workstation
- <del>(f) desktop support</del> deleted (see https://github.com/atsushieno/android-audio-plugin-framework/issues/86)
  - <del>(f1) gRPC based messaging</del>
  - <del>(f2) service instancing</del>
- [ ] (g) AAPMidiDeviceService
  - [ ] (g1) implement MIDI 1.0/2.0 interoperability in aap-lv2
  - [ ] (g2) implement MIDI 1.0/2.0 interoperability in aap-juce
  - [ ] (g3) generate valid audio output for a simple note message
  - [ ] (g4) valid MIDI 2.0 buffering in MidiDeviceService (can be downconverted to 1.0 in each backend bridge)

**Comment by atsushieno** [comment]
Now that we have 2022 edition, closing this old one.
