### ISSUE TITLE
meta: AAP roadmap 2022 edition

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/android-audio-plugin-framework#96]
This is a roadmap for the entire Android Audio Plugin Framework in 2022. It in general takes over Roadmap 2021: https://github.com/atsushieno/android-audio-plugin-framework/issues/71 . It will be occasionally updated as new tasks show up.

----

- Refactoring various pieces of existing code
  - [x] hacky aap-core PAL API
  - [x] ui-compose View/Model awkwardness
  - [x] compose WaveformDrawable
  - [x] reorganize native hosting API
  - [x] revisit extensions design, especially allow in-process function pointers (otherwise no functions are possible at all)
- Redesign ports
  - [x] general design and guidelines [#80](https://github.com/atsushieno/android-audio-plugin-framework/issues/80)
  - [ ] dynamic manifest (or skip manifest at all) [#44](https://github.com/atsushieno/android-audio-plugin-framework/issues/44)
  - [ ] audio buses configuration [#69](https://github.com/atsushieno/android-audio-plugin-framework/issues/69)
  - [x] bidirectional messaging [#73](https://github.com/atsushieno/android-audio-plugin-framework/issues/73) 
  - [ ] active sensing [#95](https://github.com/atsushieno/android-audio-plugin-framework/issues/95) , even better if we can be based on MIDI-CI, Property Exchange, and Profile Configuration.
  - [x] port size properties [#107](https://github.com/atsushieno/android-audio-plugin-framework/issues/107)
- Editor support i.e. UI protocol
  - [ ] design patch protocol over event ports (depends on the protocol design above)
  - [ ] create realtime application example (can be based on samples-host-engine) [#76](https://github.com/atsushieno/android-audio-plugin-framework/issues/76)
- GUI integration [#34](https://github.com/atsushieno/android-audio-plugin-framework/issues/34)
  - [ ] plugin in-process editor - JUCE PluginEditor integration
  - [ ] plugin out-process editor - get atsushieno/aqua working.
  - [ ] plugin out-process editor - juce_emscripten integration? (for now I don't expect the official JUCE development to go further on their own wasm support)
- Testing
  - [ ] test runner that ensures multiple plugins connection [#77](https://github.com/atsushieno/android-audio-plugin-framework/issues/77) It most likely depends on realtime application example (using the same codebase)
  - [ ] standalone test runner application and testing environment. [#40](https://github.com/atsushieno/android-audio-plugin-framework/issues/40) It is complicated because it involves multiple app apks...
- AAP core feature enhancements
  - [x] Presets, Program/Bank names and midnams [#51](https://github.com/atsushieno/android-audio-plugin-framework/issues/51)
- MidiDeviceService improvements
  - [ ] Presets integration, depends on above. We can have some option which indicates whether program/bank changes are mapped to preset changes (otherwise just send program change as a valid MIDI message; we don't wan to fall into VST3 pitfall that killed program change messages.)
  - [x] VST3 IMidiMapping alike, to make it possible to customize plugin parameters via MIDI CCs.
  - [ ] a real-world MidiDeviceService app that can be published to Play Store.
  - [ ] get MIDI 2.0 messages working again in aap-core. Hopefully with MIDI-CI and mutual conversion with MIDI 1.0.
  - [ ] MIDI 2.0 on aap-lv2 plugins
  - [ ] MIDI 2.0 on aap-juce plugins
- Publicity
  - [ ] come up with some minimum viable product feature set and "promise on unstability". (static effector, MIDI devices >> realtime effector, use as a single instrument plugin >> parallel instantiation / use in sequencer)

(Removed from roadmap 2021: Flutter UI, MOD-UI, tracktion_engine sample, desktop support - I still have some ideas but not in the list here,)

**Comment by atsushieno** [comment]
Closing as superceded by #128.
